jawah/niquests

- HISTORY.md
- setup.py
2.32.1 (2023-09-12)
**Bugfixes**
- Fix QUIC cache when using requests.request without persistent Session
**Dependencies**
- urllib3.future minimal version supported raised to 2.0.932 (ship with critical fixes)
> :bookmark: Release 2.32.1

- HISTORY.md
- src/niquests/sessions.py
- tests/test_testserver.py
Linked to https://github.com/psf/requests/issues/6026
Not really a bug per se, but
I cannot accept that a server forces our hand by raising an unexpected exception. (Namely UnicodeDecodeError)
> :bug: Fix unattended crash when server specify a non-compliant Location header on redirection

- HISTORY.md
- src/niquests/utils.py
- tests/test_utils.py
urllib3.future can overrule this (in case) to avoid a broken request being emitted.
but the reported size is correct.
> :wrench: Remove the warning about opening a file in text mode

- HISTORY.md
- src/niquests/models.py
3.0.1 (2023-09-26)
**Fixed**
- Method `head` not accepting `allow_redirect` named argument.
- `PreparedRequest` did not uppercase the HTTP verb when constructed manually.
**Changed**
- Minor code refactoring in the `text`, and `json` methods within the `Response` class to be more concise.
> :bookmark: Release 3.0.1

- src/niquests/__version__.py
3.0.2 (2023-10-01)
**Changed**
- niquests.help show more information about direct dependencies.
- urllib3.future minimal version was raised to 2.0.936 due to an important fix on the QUIC layer.
- wassima minimal version was raised to 1.0.1 in order to support certifi as a fallback in rare cases.
> :bookmark: Release 3.0.2

- HISTORY.md
- docs/api.rst
- src/niquests/__version__.py
- src/niquests/adapters.py
- src/niquests/extensions/_ocsp.py
- src/niquests/models.py
- tests/test_requests.py
3.1.1 (2023-10-11)
**Fixed**
- Fixed `Transfer-Encoding` wrongfully added to headers when body is actually of length 0. Due to the ambiguous return of `super_len` in niquests internals.
- Fixed accepting three-valued tuple for Timeout (connect, read, total) in addition to known (connect, read) tuple.
> :bookmark: Release 3.1.1

- .pre-commit-config.yaml
- HISTORY.md
- docs/user/authentication.rst
- src/niquests/__version__.py
- src/niquests/_typing.py
- src/niquests/models.py
- src/niquests/sessions.py
- tests/test_requests.py
3.1.4 (2023-10-23)
**Fixed**
- Static type checker not accepting **iterable\[str\]** for **data**. A fix in urllib3.future allows it since v2.1.902.
- Unattended override of manually provided **Authorization** if `.netrc` existed with an eligible entry. Taken from closed PR https://github.com/psf/requests/pull/6555 and initially raised in https://github.com/psf/requests/issues/3929
**Added**
- **oheaders** property in `Request`, and `PreparedRequest` in addition to `Response`.
> :bookmark: Release 3.1.4

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/community/recommended.rst
- docs/community/vulnerabilities.rst
- docs/index.rst
- docs/user/advanced.rst
- docs/user/quickstart.rst
- pyproject.toml
- requirements-dev.txt
- src/niquests/__init__.py
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/_typing.py
- src/niquests/adapters.py
- src/niquests/auth.py
- src/niquests/exceptions.py
- src/niquests/extensions/_ocsp.py
- src/niquests/extensions/_sync_to_async.py
- src/niquests/help.py
- src/niquests/models.py
- src/niquests/sessions.py
- tests/conftest.py
- tests/test_async.py
- tests/test_multiplexed.py
3.2.0 (2023-11-05)
**Changed**
- Changed method `raise_for_status` in class `Response` to return **self** in order to make the call chainable.
Idea taken from upstream https://github.com/psf/requests/issues/6215
- Bump minimal version supported for `urllib3.future` to 2.2.901 for recently introduced added features (bellow).
**Added**
- Support for multiplexed connection in HTTP/2 and HTTP/3. Concurrent requests per connection are now a thing, in synchronous code.
This feature is the real advantage of using binaries HTTP protocols.
It is disabled by default and can be enabled through `Session(multiplexed=True)`, each `Response` object will
be 'lazy' loaded. Accessing anything from returned `Response` will block the code until target response is retrieved.
Use …
> :bookmark: Release 3.2.0

- HISTORY.md
- README.md
- src/niquests/__version__.py
- src/niquests/adapters.py
3.2.1 (2023-11-06)
--------------------------
**Fixed**
- Performance issues in HTTP/2, and HTTP/3, with or without multiplexed connections.
**Changed**
- Enforced a maximum in-flight request when using multiplexed connections. Default to 200 per connection so, actually 2000 per Session (_default is 10 connections_). This can be overridden in our `HTTPAdapter` for advanced users.
> :bookmark: Release 3.2.1

- HISTORY.md
- src/niquests/__version__.py
- src/niquests/adapters.py
- src/niquests/utils.py
**Changed**
- Enforced a maximum in-flight request when using multiplexed connections. Default to 124 per connections so, actually 1240 per Session (_default is 10 connections_). This can be overriden in our `HTTPAdapter` for advanced users. This limit was changed due to constraint in `qh3`, for now we have no way to dynamically set this. We choose the safest lowest common value in h2, and qh3.
**Fixed**
- Performance issues in `get_environ_proxies()`.
> :bookmark: Release 3.2.2

- .github/FUNDING.yml
- .pre-commit-config.yaml
- HISTORY.md
- pyproject.toml
- src/niquests/__init__.py
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/_compat.py
- src/niquests/_constant.py
- src/niquests/_typing.py
- src/niquests/adapters.py
- src/niquests/cookies.py
- src/niquests/exceptions.py
- src/niquests/extensions/_ocsp.py
- src/niquests/help.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/utils.py
3.3.0 (2023-11-18)
**Added**
- Maximum of (lazy) response(s) to be resolved when calling `Session.gather(..., max_fetch = ...)`. Specifying a valid int to `max_fetch` will stop after resolving the right amount of responses.
**Changed**
- urllib3.future minimal version raised to 2.3.900 to leverage the fallback top-level package `urllib3_future`.
**Fixed**
- Runtime error when accidentally overriding `urllib3.future` by an external dependency.
- Undesirable warning yielded by `cryptography` because of a Microsoft root certificate. "Parsed a negative serial number, which is disallowed by RFC 5280."
- Consider newly registered custom CA when using `wassima.register_ca(...)`.
**Removed**
- Dependency check at runtime for `urllib3`. There are no more checks and warnings at …
> :bookmark: Release 3.3.0

- HISTORY.md
- src/niquests/__version__.py
- src/niquests/sessions.py
- src/niquests/structures.py
- tests/test_async.py
- tests/test_structures.py
**Fixed**
- CaseInsensibleDict did not properly convert HTTPHeaderDict from urllib3 thus only letting the last entry in.
- Redirect chain lead to a non waited coroutine in `AsyncSession`.
> :bookmark: Release 3.4.1

- HISTORY.md
- docs/user/advanced.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/models.py
- src/niquests/sessions.py
- tests/test_async.py
**Fixed**
- Accessing a lazy response (multiplexed enabled) that have multiple redirects did not work appropriately.
**Changed**
- Response `iter_content` and `iter_line` read chunks as they arrive by default. The default chunk size is now `-1`. `-1` mean to instruct that the chunks can be of variable sizes, depending on how packets arrives. It improves overall performances.
- urllib3.future lower bound constraint has been raised to version 2.4.904 in order to accept `-1` as a chunk size.
> :bookmark: Release 3.4.3

- HISTORY.md
- src/niquests/sessions.py
Issuing a request with `Session(multiplexed=True)` that weren't eligible (e.g. HTTP/1.1) but was redirected to an
eligible server (HTTP/2+) caused a rare error.
> :bug: Fix redirect within a multiplexed Session when first response is HTTP/1.1

- src/niquests/models.py
- src/niquests/utils.py
Refactoring Suggestions
Separation of Responsibilities: The prepare method currently does two things: it creates a new PreparedRequest object and configures it. To improve clarity, these two responsibilities could be separated into two distinct methods.
Creation Method: You could have a separate method for creating the PreparedRequest object, which would make the code more modular and reusable.
Configuration Method: Another method could be dedicated to configuring this PreparedRequest object. This method would take a PreparedRequest object as a parameter and apply all the necessary configurations.
Error when launching mypy: src/niquests/utils.py:235: error: Incompatible return value type (got "tuple[str | None, str | None]", expected "tuple[str, str] | None")  [return-value]
Suggested …
> refactoring prepare method and mypy error

- HISTORY.md
- docs/user/quickstart.rst
- pyproject.toml
- requirements-dev.txt
- src/niquests/__version__.py
- src/niquests/adapters.py
- src/niquests/sessions.py
- tests/test_multiplexed.py
**Fixed**
- Thread-safety issue when leveraging a single multiplexed connection across multiple threads.
- Apparently consumed content when allow_redirect is set to True when accessing a lazy response that follow redirects.
**Changed**
- urllib3.future lower bound constraint has been raised to version 2.5.900 in order to leverage the advanced multiplexing scheduler. This upgrade come with a noticeable performance bump in a complex multiplexed context.
**Added**
- ``Session`` constructor now accepts both ``pool_connections`` and ``pool_maxsize`` parameters to scale your pools of connections at will.
> :bookmark: Release 3.4.5

- HISTORY.md
- docs/dev/migrate.rst
- docs/index.rst
- docs/user/quickstart.rst
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/models.py
3.4.6 (2024-02-21)
**Fixed**
- Unmatched filter for deprecation warning yielded by Cryptography due to some legacy CA available in Windows having a negative serial number.
- Setting `boundary` in `Content-Type` header with no value associated (no equal sign) can cause a rare error (multipart).
- Rare racing condition while emitting too many request across a multiplexed connections.
- Spawning too many threads while using `AsyncSession` in specific contexts.
> :bookmark: Release 3.4.6

- HISTORY.md
- docs/dev/migrate.rst
- src/niquests/__version__.py
- src/niquests/adapters.py
> :zap: Fix unintentional performance regression with multiple concurrent multiplexed connection within a single Session

- .github/workflows/publish.yml
- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/community/faq.rst
- docs/community/recommended.rst
- docs/user/advanced.rst
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/api.py
- src/niquests/auth.py
- src/niquests/cookies.py
- src/niquests/exceptions.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/extensions/_picotls.py
- src/niquests/help.py
- src/niquests/hooks.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/structures.py
- src/niquests/utils.py
- tests/test_requests.py
- tests/test_utils.py
3.5.4 (2024-03-17)
**Added**
- Support to verify the peer certificate fingerprint using `verify=...` by passing a string using the following format:
`verify="sha256_748c76348778cb4a536e7ec12bc9aa559c12770bd1419c7ffe516006e1dea0ec"`. Doing so disable the certificate
usual verification and only checks for its fingerprint match.
**Fixed**
- Multiplexed request in async did not support awaitable in hooks.
- Setting `verify=...` and `cert=...` then change it for the same host did not apply to the underlying (existing) connection pool.
**Misc**
- Overall performance improvements in both async and sync requests.
- Update pre-commit dependencies (ruff, pyupgrade, and mypy).
- Fixed SessionRedirect in tests that produced an incomplete Response instance that wasn't suitable for …
> :bookmark: Release 3.5.4

- HISTORY.md
- README.md
- docs/index.rst
- docs/user/quickstart.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/_compat.py
- src/niquests/adapters.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/models.py
- src/niquests/sessions.py
- tests/test_async.py
- tests/test_live.py
3.5.5 (2024-03-25)
**Added**
- Support for Happy Eyeballs. This feature is disabled by default, you must pass `happy_eyeballs=True` within your session constructor or http adapter in order to leverage this.
**Fixed**
- Missed close implementation in AsyncSession causing the underlying poolmanager to remain open.
- Additional OCSP requests (following a redirect) did not use specified custom DNS resolver.
**Changed**
- urllib3.future lower bound constraint has been raised to version 2.7.900 for the newly added happy eyeballs feature.
> :sparkle: Support for Happy Eyeballs

- docs/community/recommended.rst
- src/niquests/sessions.py
Applied remarks collected from https://github.com/panodata/grafana-client/pull/146 and https://github.com/panodata/grafana-wtf/pull/130
> :art: Better UX for users migrating off Requests

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/community/faq.rst
- docs/user/advanced.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/help.py
- src/niquests/sessions.py
3.6.0 (2024-04-20)
**Added**
- Support for qh3 version 1.0.0
This qh3 release enable a greater flexibility by dropping cryptography. We had to adapt the OCSP code as we
relied on cryptography. HTTP/3 experience is greatly improved.
**Changed**
- urllib3.future lower bound constraint has been raised to version 2.7.904 to ensure support for the last qh3 release.
**Fixed**
- Improved compatibility with third party mocking tool that are bound to requests.
- OCSP check did not warn if the HTTP server responded with a non 2xx response in strict mode.
> :sparkle: Adjustment for HTTP/3 and OCSP simplifications that came with qh3 1.0+

- HISTORY.md
- src/niquests/__version__.py
- src/niquests/_compat.py
Came up with someone that attempted to break his environment by doing:
```
pip install niquests requests
pip uninstall requests urllib3
python -c "import niquests"
```
in the given order.
> :bug: Improve handling broken environment with a graceful error

- .github/workflows/run-tests.yml
- HISTORY.md
- MANIFEST.in
- README.md
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/help.py
**Fixed**
- "Help" program `python -m niquests.help` that depended on h2 while not required anymore.
- Minor performance regression in async while checking OCSP when certificate isn't eligible (e.g. no OCSP url provided).
> :bookmark: Release 3.6.2

- src/niquests/models.py
- tests/test_requests.py
This addresses #118, inspired by the code in [requests](https://github.com/psf/requests/blob/2d5f54779ad174035c5437b3b3c1146b0eaf60fe/src/requests/models.py#L122).
Essentially this PR will allow encoding any non-iterable object as string. This is a general solution to the specific problem in #118. Since `None` is not iterable, it is encoded "None". Similarly, any non-iterable object will be encoded as `str(obj)`.
> 🐛 Fix encoding data with None values and more

- src/niquests/_async.py
hi, you resolve this issue #79 in PR #87  and this true. However, you still have an unused attribute
I re-checked the generation of threads and indeed the work is happening in one thread, and you can see it under the hood, thanks
```python
import niquests
import threading
import asyncio
async def main():
s = niquests.AsyncSession()
print(threading.enumerate())
task1 = asyncio.create_task(s.get('https://google.com/search?q=hi'))
task2 = asyncio.create_task(s.get('https://google.com/search?q=привет'))
print(threading.enumerate())
await task1
await task2
if __name__ == "__main__":
asyncio.run(main())
```
result
```text
[<_MainThread(MainThread, started 6712)>]
[<_MainThread(MainThread, started 6712)>]
```
> remove unused `disable_thread: bool = False  # no-op since v3.5`

- HISTORY.md
- src/niquests/__version__.py
- src/niquests/cookies.py
- tests/conftest.py
- tests/test_requests.py
The standard library does not allow this special
domain. Researches showed that a valid domain should have at least two dots (e.g. abc.com. and xyz.tld. but not com.).
Public suffixes cannot be used as a cookie domain for security reasons, but as `localhost` isn't one we are explicitly
allowing it. Reported in https://github.com/httpie/cli/issues/602
`RequestsCookieJar` set a default policy that circumvent that limitation, if you specified a custom cookie policy then this
fix won't be applied.
> :bug: Support `localhost` as a valid domain for cookies

- HISTORY.md
- src/niquests/__init__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/sessions.py
- src/niquests/utils.py
3.6.5 (2024-05-22)
**Fixed**
- Support `localhost` as a valid domain for cookies. The standard library does not allow this special
domain. Researches showed that a valid domain should have at least two dots (e.g. abc.com. and xyz.tld. but not com.).
Public suffixes cannot be used as a cookie domain for security reasons, but as `localhost` isn't one we are explicitly
allowing it. Reported in https://github.com/httpie/cli/issues/602
`RequestsCookieJar` set a default policy that circumvent that limitation, if you specified a custom cookie policy then this
fix won't be applied.
**Changed**
- Lazy load the OCSP extension in order to improve the import performance.
**Removed**
- Class variable `disable_thread` in `AsyncSession` that is no longer relevant since the native …
> :zap: Lazy load the OCSP extension in order to improve the import performance

- HISTORY.md
- README.md
- docs/user/advanced.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/api.py
- src/niquests/models.py
- src/niquests/sessions.py
**Added**
- TransferProgress tracking in Response when downloading using `stream=True` based on the Content-Length. (#127) There's no easy way to track the "real" amount of bytes consumed using "iter_content" when the remote is sending a compressed body. This change makes it possible to track the amount of bytes consumed. The `Response` object now contain a property named `download_progress` that is either `None` or a `TransferProgress` object.
- HTTP/2 with prior knowledge over TLS or via an unencrypted connection. `disable_http1` toggle is now available through your `Session` constructor. In consequence, you may leverage all HTTP/2 capabilities like multiplexing using a plain (e.g. non-TLS) socket. You may enable/disable any protocols per Session object (but not all of them at once!). …
> :bookmark: Release 3.7.0

- HISTORY.md
- src/niquests/_typing.py
- src/niquests/models.py
Add a callable object to the `HttpAuthenticationType` type definition.
A type checking error occurs when a callable object is given as the `auth` argument.
<details>
<summary>Reproduction code</summary>
```python
import niquests
def pizza_auth(request: niquests.PreparedRequest) -> niquests.PreparedRequest:
if request.headers:
request.headers["X-Pizza"] = "Token"
return request
def test_callable_auth():
r = niquests.get("https://httpbin.org/get", auth=pizza_auth)
print(r.json()["headers"])
if __name__ == "__main__":
test_callable_auth()
```
</details>
This is allowed at runtime.
https://github.com/jawah/niquests/blob/d83ab6b98e317bbf82ea950a693fce1fc95936a3/src/niquests/models.py#L615-L647
> Fix HttpAuthenticationType to add callable

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/index.rst
- docs/user/advanced.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/help.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/utils.py
- tests/test_async.py
- tests/test_live.py
**Added**
- Support for HTTP Trailers.
- Help script now yield warnings if update are available for each sub dependencies.
**Fixed**
- Setting a list of Resolver.
**Changed**
- urllib3-future lower bound version is raised to 2.9.900 (for http trailer support).
- relax strict kwargs passing in Session adapters (required for some plugins).
> :bookmark: Release 3.8.0

- .github/workflows/run-tests.yml
- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/community/faq.rst
- docs/index.rst
- docs/user/advanced.rst
- docs/user/quickstart.rst
- noxfile.py
- pyproject.toml
- requirements-dev.txt
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/cookies.py
- src/niquests/hooks.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/utils.py
- tests/test_async.py
- tests/test_hooks.py
- tests/test_live.py
- tests/test_lowlevel.py
- tests/test_multiplexed.py
- tests/test_ocsp.py
- tests/test_websocket.py
**Added**
- Support for WebSocket over HTTP/1, HTTP/2 and HTTP/3. It brings a unified API that makes you leverage our powerful features like Happy Eyeballs, SOCKS/HTTP/HTTPS proxies, thread/task safety etc...
- Hook for catching early responses like "103 Early Hints".
**Fixed**
- Informational responses are fully supported over HTTP/1, HTTP/2 and HTTP/3.
**Changed**
- urllib3-future lower bound version is raised to 2.10.900.
> :bookmark: Release 3.9.0

- README.md
I'm very excited about the new WebSocket support in niquests! Just to clarify, though, aiohttp is already a powerful WebSocket (HTTP/1.1) client:
https://docs.aiohttp.org/en/stable/client_quickstart.html#websockets
> Fix aiohttp feature comparison in README.md

- .github/workflows/run-tests.yml
- .pre-commit-config.yaml
- HISTORY.md
- docs/user/advanced.rst
- docs/user/quickstart.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/utils.py
3.9.1 (2024-10-13)
**Fixed**
- Exception leak from urllib3-future when using WebSocket.
- Enforcing HTTP/3 in an AsyncSession. (#152)
- Adapter kwargs fallback to support old Requests extensions.
- Type hint for ``Response.extension`` linked to the generic interface instead of the inherited ones.
- Accessing WS over HTTP/2+ using the synchronous session object.
**Misc**
- Documentation improvement for in-memory certificates and WebSocket use cases.  (#151)
**Changed**
- urllib3-future lower bound version is raised to 2.10.904 to ensure exception are properly translated into urllib3-future ones for WS.
> Release 3.9.1

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/user/quickstart.rst
- pyproject.toml
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/adapters.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/extensions/_picotls.py
- src/niquests/sessions.py
3.10.0 (2024-10-21)
**Added**
- Automatic Advanced Keep-Alive for HTTP/2 and HTTP/3 over QUIC by sending PING frames.
New Session, and Adapter parameters are now available: `keepalive_delay`, and `keepalive_idle_window`.
This greatly improves your daily experience working with HTTP/2+ remote peers.
**Fixed**
- Unshielded picotls assertion error in Python < 3.10 when trying to fetch the peer intermediate certificate. (#157)
> Release 3.10

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- src/niquests/__version__.py
- src/niquests/adapters.py
- src/niquests/models.py
> :bug: fix exception leak from urllib3-future when resolving lazy responses

- .github/workflows/run-tests.yml
- HISTORY.md
- docs/dev/migrate.rst
- docs/user/advanced.rst
- docs/user/quickstart.rst
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/sessions.py
- tests/test_testserver.py
3.10.2 (2024-10-25)
**Fixed**
- Ensure `stream`, and `verify` both defaults to your ``Session`` parameters. (#165)
> Fix in session defaults for verify, and stream

- HISTORY.md
- src/niquests/_async.py
3.11.0 (2024-11-20)
**Added**
- base_url parameter to `niquests.Session` or `niquests.AsyncSession`. automatically prefix every request emitted with it. (#179)
**Fixed**
- warning about coroutine method 'aclose' of 'AsyncSession.resolve_redirects' was never awaited.
> :bug: fix warning about coroutine method 'aclose' of 'AsyncSession.resolve_redirects' was never awaited

- .coveragerc
- HISTORY.md
- noxfile.py
- requirements-dev.txt
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/_typing.py
- src/niquests/adapters.py
- src/niquests/cookies.py
- src/niquests/exceptions.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/models.py
- src/niquests/sessions.py
- src/niquests/structures.py
- src/niquests/utils.py
- tests/test_ocsp.py
3.11.3 (2024-12-13)
**Fixed**
- Static type checker getting confused around ``AsyncSession`` and attached overloads (``AsyncResponse`` or ``Response``). (#185)
**Changed**
- Default keepalive (HTTP/2, and HTTP/3) changed to 1 hour. In conformance with urllib3-future.
**Removed**
- Automatic resolution of pending lazy responses if there are too many of them.
Previously, we hardcoded a limit of 128 * NUM_CONN_POOL maximum inflight (aka. unresolved/lazy) response.
This was unrealistic due to a number of factors like (but not limited to):
A) remote peers can choose at will the max streams.
B) we can have multiple pool with multiple (varying) max capacities.
C) retrieving max streams per pool per conn is a very costly procedure (in terms of performance).
We will revisit …
> Release 3.11.3

- .pre-commit-config.yaml
- HISTORY.md
- src/niquests/__init__.py
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/extensions/_picotls.py
- src/niquests/sessions.py
- src/niquests/structures.py
3.12.0 (2025-01-01)
**Fixed**
- Restoring the state of `AsyncSession` through pickle.
- Typing definition for query parameter not accepting `None` as values. (#193)
- Overload incorrect definition for `AsyncSession::get`. (#192)
**Added**
- Support for `PathLike` objects for `verify` parameter when passing a ca bundle path. (#194)
- Caching and restoring OCSP state through pickling `Session` or `AsyncSession`.
- Caching and restoring QUIC known compatible hosts through pickling `Session` or `AsyncSession`.
- Shortcut convenient access to `Retry` and `Timeout` configuration objects in top-level import.
> Release 3.12

- src/niquests/models.py
I noticed that the content-type looked like this:
`"Content-Type": "application/json; charset=\"utf-8\"",`
and then I checked the corresponding RFC (7231) to see if that's valid.
It is valid, but not the preferred way.
---
Update: [reference to RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-media-type)
> chore(models): use preferred notation for JSON content-type

- .pre-commit-config.yaml
- HISTORY.md
- README.md
- docs/api.rst
- docs/community/extensions.rst
- docs/community/faq.rst
- docs/conf.py
- docs/dev/migrate.rst
- docs/index.rst
- docs/requirements.txt
- docs/user/advanced.rst
- docs/user/install.rst
- docs/user/quickstart.rst
- pyproject.toml
- src/niquests/__init__.py
- src/niquests/__version__.py
- src/niquests/_async.py
- src/niquests/_typing.py
- src/niquests/adapters.py
- src/niquests/cookies.py
- src/niquests/exceptions.py
- src/niquests/extensions/_async_ocsp.py
- src/niquests/extensions/_ocsp.py
- src/niquests/extensions/_picotls.py
- src/niquests/models.py
- src/niquests/packages.py
- src/niquests/sessions.py
- src/niquests/utils.py
- tests/test_websocket.py
3.13.1 (2025-03-09)
**Added**
- Internal shortcut to urllib3-future as `niquests.packages.urllib3`. This immediately helps end-user migrating
from Requests to Niquests and avoid the confusion around `urllib3` and `urllib3-future`.
The package own code benefit from it. `idna`, `charset_normalizer` (+ aliased as `chardet`) can be used also.
**Misc**
- The documentation is improved. Especially around sync/async examples and migration snippets.
> Release 3.13.1

- src/niquests/models.py
- tests/test_async.py
Hi there,
Trying to explicitly call the `.close` method from an `AsyncResponse` produced by `AsyncSession` produces a runtime warning since the `close` method of urllib3's `AsyncHTTPResponse` is never awaited.
You can reproduce it with the following code
```python
import asyncio
import niquests
async def main():
session = niquests.AsyncSession()
try:
response = await session.get("https://example.com", stream=True)
finally:
await response.close()
asyncio.run(main())
```
I'm not entirely sure if this is a bug but this at least gets rid of the runtime warning
> Add missing await in AsyncResponse .close method

- src/niquests/async_session.py
- src/niquests/sessions.py
- tests/test_requests.py
As this snippet showcases, niquests does not fire session hooks for the pre_request hook event.
```py
import niquests
def pre_request_session_hook(request: niquests.PreparedRequest):
"""Pre-request session hook."""
print("Pre-request session hook fired")
s = niquests.Session()
s.hooks["pre_request"] = [pre_request_session_hook]
response = s.get("https://httpbin.org/get")
```
output
` `
This pull request modifies this behaviour for the expected one.
> Fixes issue where session hooks are not fired for the pre_request hook.

- HISTORY.md
- docs/dev/httpx.rst
- src/niquests/__version__.py
- src/niquests/api.py
- src/niquests/async_api.py
3.14.1 (2025-04-19)
**Fixed**
- Prevent accessing lazy attr if it does not exist (e.g. requests_cache mixin) (#243)
- Session hooks are not fired for the pre_request hook. (#242)
- OCSP redundant calls made from session-less requests.
> Release 3.14.1

- HISTORY.md
- src/niquests/__version__.py
- src/niquests/async_session.py
- src/niquests/sessions.py
- tests/test_crl.py
3.15.2 (2025-08-16)
**Fixed**
- The return type of `CaseInsensitiveDict.items()` could be a `list` instead of an expected `tuple`. (#276)
- Omitting hooks (keys) in `Session.hooks` dict causing an error at merge with request specific hooks.
- CRL cache not persisted when pickling `Session`.
> Release 3.15.2

- docs/community/extensions.rst
close #281 
handle the "many responses" case.
> Update requests_mock migration example
