jawah/niquests

HISTORY.md
setup.py
src/niquests/__init__.py
src/niquests/compat.py
src/niquests/help.py
src/niquests/models.py
src/niquests/packages.py
src/niquests/utils.py
tests/test_utils.py

And :fire: remove chardet legacy support.

:art: Refactor the encoding detection feature

---

HISTORY.md
src/niquests/models.py
src/niquests/utils.py
tests/test_requests.py
tests/test_utils.py

and make text method from Response stricter around "not-decodable content"

:fire: Remove ISO-8859-1 charset fall back

---

.github/workflows/run-tests.yml
.pre-commit-config.yaml
HISTORY.md
README.md
setup.py
src/niquests/__init__.py
src/niquests/__version__.py
src/niquests/_internal_utils.py
src/niquests/_typing.py
src/niquests/adapters.py
src/niquests/api.py
src/niquests/auth.py
src/niquests/compat.py
src/niquests/cookies.py
src/niquests/help.py
src/niquests/hooks.py
src/niquests/models.py
src/niquests/sessions.py
src/niquests/utils.py
tests/test_requests.py
tests/test_utils.py

This should cover almost 100% of use cases.
Wasn't easy.

:sparkle: Added static type annotations thorough the whole package

---

HISTORY.md
src/niquests/sessions.py

Linked to https://github.com/psf/requests/issues/6118
Taken from https://github.com/psf/requests/pull/6119

:bug: Fix undesirable dict mutation for proxies when merging with proxies in environment variables

---

.pre-commit-config.yaml
HISTORY.md
src/niquests/_typing.py
src/niquests/adapters.py
src/niquests/api.py
src/niquests/exceptions.py
src/niquests/hooks.py
src/niquests/models.py
src/niquests/sessions.py
src/niquests/structures.py
src/niquests/utils.py

Still unable to enforce 'strict' with mypy but not far.
Can't be done properly while supporting Python 3.7
Should be done in the next-minor.

:art: Improve overall static typing experience

---

src/niquests/__init__.py

Remove charset-normalizer check in top-lvl import and change the RequestsDependencyWarning text
Also, remove the unused filter on FileModeWarning as it was removed in 3.0

:wrench: Refactor checks in top-level import pkg

---

HISTORY.md
README.md
src/niquests/__version__.py
src/niquests/_internal_utils.py
src/niquests/adapters.py
src/niquests/extensions/_ocsp.py
src/niquests/models.py
src/niquests/sessions.py
src/niquests/structures.py
src/niquests/utils.py
tests/test_requests.py
tests/test_utils.py
tests/utils.py

**Fixed**
- Overall performance improvement.
- Racing condition in `HTTPAdapter` with multiplexed enabled while in threads.
**Removed**
- Checks for header validity as it is duplicated (upstream does it already). Warning: Function `check_header_validity` has been removed. It was not public in the first place.
**Changed**
- Cached proxies from environment to avoid unnecessary scan on each request.

:bookmark: Release 3.2.3

---

HISTORY.md
src/niquests/__version__.py
src/niquests/adapters.py
src/niquests/models.py
src/niquests/structures.py
tests/test_requests.py

3.2.4 (2023-11-15)
**Fixed**
- Compatibility with some third-party mock tools.
**Changed**
- Relax IllegalHeader constraint when value is an integer, or float.

:bug: Fix compatibility with some third-party mock tools

---

HISTORY.md
src/niquests/__version__.py
src/niquests/models.py
src/niquests/structures.py
src/niquests/utils.py

**Fixed**
- ImportError in an attempt to retrieve `ConnectionInfo`.
**Changed**
- General performance improvements.

:bookmark: Release 3.5.2

---

.github/workflows/cohabitation-test.yml
noxfile.py
src/niquests/adapters.py
tests/test_live.py
tests/test_requests.py

Made to ensure #90 never occurs again.

:heavy_check_mark: Add urllib3 cohabitation test

---

README.md

📈 add stats / benchmarks

---

HISTORY.md
src/niquests/__version__.py
src/niquests/_async.py
src/niquests/adapters.py
src/niquests/cookies.py
src/niquests/sessions.py

**Fixed**
- Fixed encoding data with None values and other objects. This was a regression introduced in our v3. #119
**Changed**
- Various minor performance improvements.

:bookmark: Release 3.6.3

---

HISTORY.md
pyproject.toml
src/niquests/__version__.py
src/niquests/extensions/_async_ocsp.py
src/niquests/extensions/_ocsp.py
src/niquests/sessions.py
src/niquests/structures.py

also avoid parsing x509 certificate many times for the same remote peer

:zap: overall performance improvement by reducing redundant iterations from requests era

---

HISTORY.md
pyproject.toml
src/niquests/__version__.py
src/niquests/structures.py
tests/test_async.py

:bug: fix dummylock injected into asyncsession for cookies

---

docs/user/quickstart.rst
src/niquests/models.py

Hello and greetings,
This PR fixes the broken links for `kiss-headers` in documentation.
I saw this while reading the docs so I thought I should PR a fix :P
P.S. Thank you so much for making niquests ❤️ It is simply amazing!

fix `kiss-headers` links in docs

---

HISTORY.md
src/niquests/__version__.py
src/niquests/adapters.py

:bug: fix resolving lazy responses when emitted through a SOCKS, HTTP or HTTPS proxy

---

docs/user/advanced.rst
src/niquests/__version__.py
src/niquests/_async.py
src/niquests/models.py
src/niquests/sessions.py
tests/test_async.py
tests/test_live.py
tests/test_requests.py

close https://github.com/jawah/niquests/issues/179
answer a long demanded feature, straightforward to implement and test.

:sparkle: Add base_url setting in Session/AsyncSession

---

src/niquests/_typing.py
src/niquests/models.py

:wrench: accept None values in typing definition for QueryParameterType

---

src/niquests/adapters.py

close https://github.com/jawah/niquests/issues/201

:sparkle: add repr in (Async)HTTPAdapter

---

docs/_templates/base.html
docs/api.rst
docs/index.rst
docs/user/authentication.rst
docs/user/install.rst
docs/user/quickstart.rst

- more meta descriptions
- more usage of animated terminal
- more async/sync tabs

:pencil: documentation improvement

---

src/niquests/async_session.py
src/niquests/sessions.py

… 
close https://github.com/jawah/niquests/issues/241

:bug: prevent accessing lazy attr if don't exist (e.g. requests_cache mixin)

---

docs/dev/httpx.rst
docs/dev/migrate.rst
docs/index.rst

:pencil: httpx to niquests guide

---

docs/dev/contributing.rst

Fixes https://github.com/jawah/niquests/issues/252

Linkrot fix

---

HISTORY.md
src/niquests/structures.py
tests/test_structures.py

:bug: Fix the return type of CaseInsensitiveDict.items() that mixed list and tuple
